name: CallPrint
on:  
  workflow_dispatch:
    inputs:
      change-request:
        description: 'Enter the Change Request Number'
        required: false
        default: ''
        type: string

jobs:
  PrintLine:
    runs-on: [self-hosted, linux, X64]

  print:
    permissions:
       contents: write
       id-token: write
    if: ${{ inputs.change-request != '' }}
    uses: ./.github/workflows/print.yml
