name: CallPrint
on:  
  workflow_dispatch:

jobs:
  PrintLine:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: printLine
        if: ${{ github.head_ref == 'main' }}
        # Runs the tests, linters, etc. on the code that will be merged into the base branch
        uses: ./.github/workflows/print.yml
