name: CallPrint
on:  
  workflow_dispatch:
    inputs:
      change-request:
        description: 'Enter the Change Request Number'
        required: false
        default: ''
        type: string

jobs:
  print:
    if: ${{ inputs.change-request != '' }}
    uses: ./.github/workflows/print.yml
