name: GetInput
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      change-request:
        description: 'Enter the Change Request Number'
        required: false
        default: ''
        type: string
jobs:
  PrintLine:
    runs-on: [self-hosted, linux, X64]

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout repository content
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Change Request
        if: ${{ inputs.change-request != '' }}
        shell: bash
        run: |
          echo "Change Request Number: ${{ inputs.change-request }}"

      - name: check_input_data
        id: check_input
        run: |      
          if  ${{ inputs.change-request != '' }}; then
              echo "Change Request Number --------- : ${{ inputs.change-request }}"
          else
              echo "Branch=true" >> $GITHUB_OUTPUT
          fi    

      - name: Set global variables
        if: ${{ steps.check_input.outputs.Branch == 'true' }}
        shell: bash
        run: |
          echo "GITHUB_REPOSITORY is $GITHUB_REPOSITORY"          
          REPO=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          echo "repo_name=$REPO" >> $GITHUB_ENV
          echo "branch_name=$BRANCH" >> $GITHUB_ENV          
          echo "Repo is $REPO"
          echo "Branch name is $BRANCH"

       
