name: PrintSample
on:
  pull_request:
    types: [opened, reopened]

jobs:
  PrintLine:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: printLine
        run:
           echo "From Github Actions triggered on pull_request event"
